from __future__ import annotations

from backend.ingest.base import (
    SourceDefinition,
    fetch_algorithmic_finance,
    fetch_annals_of_applied_statistics,
    fetch_arxiv_multi_category,
    fetch_generic_html,
    fetch_jasss,
    fetch_jmlr,
    fetch_neurips,
    fetch_plos_computational_biology,
    fetch_private_placeholder,
    fetch_ssrn,
)


PRIVATE_PUBLISHER_NOTE = (
    "Private source. Reach out to your university library, institutional research portal, "
    "or the publisher's sales/support team for subscription access."
)


SOURCE_REGISTRY = {
    "arxiv_qfin_math_cs_stat": SourceDefinition(
        source_id="arxiv_qfin_math_cs_stat",
        label="arXiv (q-fin, math, cs, stat, cond-mat)",
        main_category="Academic & Preprints",
        sub_category="Preprints (The Core)",
        homepage_url="https://arxiv.org/",
        access="Public",
        notes="Uses the arXiv API across q-fin, math, cs, stat, and cond-mat, then downloads the latest paper PDF in-range.",
        fetcher=fetch_arxiv_multi_category,
    ),
    "ssrn": SourceDefinition(
        source_id="ssrn",
        label="SSRN",
        main_category="Academic & Preprints",
        sub_category="Preprints (The Core)",
        homepage_url="https://papers.ssrn.com/sol3/DisplayJournalBrowse.cfm",
        access="Public",
        notes="Dedicated SSRN finance adapter using official SSRN journal pages.",
        fetcher=fetch_ssrn,
    ),
    "algorithmic_finance": SourceDefinition(
        source_id="algorithmic_finance",
        label="Algorithmic Finance",
        main_category="Academic & Preprints",
        sub_category="Core Quant Finance",
        homepage_url="https://algorithmicfinance.org/",
        access="Public",
        notes="Dedicated journal-site adapter for article pages and PDFs.",
        fetcher=fetch_algorithmic_finance,
    ),
    "mathematical_finance": SourceDefinition(
        source_id="mathematical_finance",
        label="Mathematical Finance",
        main_category="Academic & Preprints",
        sub_category="Core Quant Finance",
        homepage_url="https://onlinelibrary.wiley.com/journal/14679965",
        access="Private",
        notes=f"{PRIVATE_PUBLISHER_NOTE} URL: https://onlinelibrary.wiley.com/journal/14679965",
        fetcher=fetch_private_placeholder,
    ),
    "finance_and_stochastics": SourceDefinition(
        source_id="finance_and_stochastics",
        label="Finance and Stochastics",
        main_category="Academic & Preprints",
        sub_category="Core Quant Finance",
        homepage_url="https://www.springer.com/journal/780",
        access="Private",
        notes=f"{PRIVATE_PUBLISHER_NOTE} URL: https://www.springer.com/journal/780",
        fetcher=fetch_private_placeholder,
    ),
    "quantitative_finance": SourceDefinition(
        source_id="quantitative_finance",
        label="Quantitative Finance",
        main_category="Academic & Preprints",
        sub_category="Core Quant Finance",
        homepage_url="https://www.tandfonline.com/toc/rquf20/current",
        access="Private",
        notes=f"{PRIVATE_PUBLISHER_NOTE} URL: https://www.tandfonline.com/toc/rquf20/current",
        fetcher=fetch_private_placeholder,
    ),
    "journal_of_computational_finance": SourceDefinition(
        source_id="journal_of_computational_finance",
        label="Journal of Computational Finance",
        main_category="Academic & Preprints",
        sub_category="Core Quant Finance",
        homepage_url="https://www.risk.net/journal-of-computational-finance",
        access="Private",
        notes="Private source. Reach out to Risk.net enterprise sales or your firm's research library. URL: https://www.risk.net/journal-of-computational-finance",
        fetcher=fetch_private_placeholder,
    ),
    "siam_journal_on_financial_mathematics": SourceDefinition(
        source_id="siam_journal_on_financial_mathematics",
        label="SIAM Journal on Financial Mathematics",
        main_category="Academic & Preprints",
        sub_category="Core Quant Finance",
        homepage_url="https://www.siam.org/publications/journals/siam-journal-on-financial-mathematics-sifin",
        access="Private",
        notes=f"{PRIVATE_PUBLISHER_NOTE} URL: https://www.siam.org/publications/journals/siam-journal-on-financial-mathematics-sifin",
        fetcher=fetch_private_placeholder,
    ),
    "risk_net_cutting_edge": SourceDefinition(
        source_id="risk_net_cutting_edge",
        label="Risk.net (Cutting Edge)",
        main_category="Academic & Preprints",
        sub_category="Core Quant Finance",
        homepage_url="https://www.risk.net/cutting-edge",
        access="Private",
        notes="Private source. Reach out to Risk.net enterprise sales or your firm's research library. URL: https://www.risk.net/cutting-edge",
        fetcher=fetch_private_placeholder,
    ),
    "journal_of_portfolio_management": SourceDefinition(
        source_id="journal_of_portfolio_management",
        label="Journal of Portfolio Management",
        main_category="Academic & Preprints",
        sub_category="Core Quant Finance",
        homepage_url="https://jpm.pm-research.com/",
        access="Private",
        notes="Private source. Reach out to PM Research or your institutional library. URL: https://jpm.pm-research.com/",
        fetcher=fetch_private_placeholder,
    ),
    "journal_of_risk": SourceDefinition(
        source_id="journal_of_risk",
        label="Journal of Risk",
        main_category="Academic & Preprints",
        sub_category="Core Quant Finance",
        homepage_url="https://www.risk.net/journal-of-risk",
        access="Private",
        notes="Private source. Reach out to Risk.net enterprise sales or your firm's research library. URL: https://www.risk.net/journal-of-risk",
        fetcher=fetch_private_placeholder,
    ),
    "journal_of_finance": SourceDefinition(
        source_id="journal_of_finance",
        label="Journal of Finance",
        main_category="Academic & Preprints",
        sub_category='Financial Econ ("Big Four")',
        homepage_url="https://afajof.org/",
        access="Private",
        notes="Private source. Reach out to the American Finance Association or your institutional library. URL: https://afajof.org/",
        fetcher=fetch_private_placeholder,
    ),
    "journal_of_financial_economics": SourceDefinition(
        source_id="journal_of_financial_economics",
        label="Journal of Financial Economics",
        main_category="Academic & Preprints",
        sub_category='Financial Econ ("Big Four")',
        homepage_url="https://www.journals.elsevier.com/journal-of-financial-economics",
        access="Private",
        notes=f"{PRIVATE_PUBLISHER_NOTE} URL: https://www.journals.elsevier.com/journal-of-financial-economics",
        fetcher=fetch_private_placeholder,
    ),
    "review_of_financial_studies": SourceDefinition(
        source_id="review_of_financial_studies",
        label="Review of Financial Studies",
        main_category="Academic & Preprints",
        sub_category='Financial Econ ("Big Four")',
        homepage_url="https://academic.oup.com/rfs",
        access="Private",
        notes="Private source. Reach out to Oxford University Press or your institutional library. URL: https://academic.oup.com/rfs",
        fetcher=fetch_private_placeholder,
    ),
    "journal_of_financial_and_quantitative_analysis": SourceDefinition(
        source_id="journal_of_financial_and_quantitative_analysis",
        label="Journal of Financial and Quantitative Analysis",
        main_category="Academic & Preprints",
        sub_category='Financial Econ ("Big Four")',
        homepage_url="https://www.cambridge.org/core/journals/journal-of-financial-and-quantitative-analysis",
        access="Private",
        notes="Private source. Reach out to Cambridge University Press or your institutional library. URL: https://www.cambridge.org/core/journals/journal-of-financial-and-quantitative-analysis",
        fetcher=fetch_private_placeholder,
    ),
    "journal_of_machine_learning_research": SourceDefinition(
        source_id="journal_of_machine_learning_research",
        label="Journal of Machine Learning Research",
        main_category="Academic & Preprints",
        sub_category="CS, ML & AI",
        homepage_url="https://jmlr.org/papers",
        access="Public",
        notes="Dedicated adapter for the current JMLR volume table of contents.",
        fetcher=fetch_jmlr,
    ),
    "neurips_icml_proceedings": SourceDefinition(
        source_id="neurips_icml_proceedings",
        label="NeurIPS / ICML Proceedings",
        main_category="Academic & Preprints",
        sub_category="CS, ML & AI",
        homepage_url="https://papers.nips.cc/",
        access="Public",
        notes="Dedicated adapter for the latest NeurIPS proceedings volume. Consider splitting ICML into a separate adapter later.",
        fetcher=fetch_neurips,
    ),
    "annals_of_applied_statistics": SourceDefinition(
        source_id="annals_of_applied_statistics",
        label="Annals of Applied Statistics",
        main_category="Academic & Preprints",
        sub_category="Math, Stats & Ops",
        homepage_url="https://imstat.org/journals-and-publications/annals-of-applied-statistics/",
        access="Public",
        notes="Dedicated adapter using the public Project Euclid journal pages.",
        fetcher=fetch_annals_of_applied_statistics,
    ),
    "operations_research_informs": SourceDefinition(
        source_id="operations_research_informs",
        label="Operations Research (INFORMS)",
        main_category="Academic & Preprints",
        sub_category="Math, Stats & Ops",
        homepage_url="https://pubsonline.informs.org/journal/opre",
        access="Private",
        notes="Private source. Reach out to INFORMS subscriptions or your institutional library. URL: https://pubsonline.informs.org/journal/opre",
        fetcher=fetch_private_placeholder,
    ),
    "journal_of_the_american_statistical_association": SourceDefinition(
        source_id="journal_of_the_american_statistical_association",
        label="Journal of the American Statistical Association",
        main_category="Academic & Preprints",
        sub_category="Math, Stats & Ops",
        homepage_url="https://www.amstat.org/publications/jasa",
        access="Private",
        notes="Private source. Reach out to the American Statistical Association, Taylor & Francis, or your institutional library. URL: https://www.amstat.org/publications/jasa",
        fetcher=fetch_private_placeholder,
    ),
    "acm_transactions_on_mathematical_software": SourceDefinition(
        source_id="acm_transactions_on_mathematical_software",
        label="ACM Trans. on Mathematical Software",
        main_category="Academic & Preprints",
        sub_category="CS, ML & AI",
        homepage_url="https://dl.acm.org/journal/toms",
        access="Private",
        notes="Private source. Reach out to ACM DL or your institutional library. URL: https://dl.acm.org/journal/toms",
        fetcher=fetch_private_placeholder,
    ),
    "physical_review_e": SourceDefinition(
        source_id="physical_review_e",
        label="Physical Review E",
        main_category="Academic & Preprints",
        sub_category="Physics & Econophysics",
        homepage_url="https://journals.aps.org/pre",
        access="Private",
        notes="Private source. Reach out to APS institutional sales or your library. URL: https://journals.aps.org/pre",
        fetcher=fetch_private_placeholder,
    ),
    "physica_a_statistical_mechanics": SourceDefinition(
        source_id="physica_a_statistical_mechanics",
        label="Physica A: Statistical Mechanics",
        main_category="Academic & Preprints",
        sub_category="Physics & Econophysics",
        homepage_url="https://www.sciencedirect.com/journal/physica-a-statistical-mechanics-and-its-applications",
        access="Private",
        notes=f"{PRIVATE_PUBLISHER_NOTE} URL: https://www.sciencedirect.com/journal/physica-a-statistical-mechanics-and-its-applications",
        fetcher=fetch_private_placeholder,
    ),
    "chaos_solitons_and_fractals": SourceDefinition(
        source_id="chaos_solitons_and_fractals",
        label="Chaos, Solitons & Fractals",
        main_category="Academic & Preprints",
        sub_category="Physics & Econophysics",
        homepage_url="https://www.sciencedirect.com/journal/chaos-solitons-and-fractals",
        access="Private",
        notes=f"{PRIVATE_PUBLISHER_NOTE} URL: https://www.sciencedirect.com/journal/chaos-solitons-and-fractals",
        fetcher=fetch_private_placeholder,
    ),
    "european_physical_journal_b": SourceDefinition(
        source_id="european_physical_journal_b",
        label="European Physical Journal B",
        main_category="Academic & Preprints",
        sub_category="Physics & Econophysics",
        homepage_url="https://www.springer.com/journal/10051",
        access="Private",
        notes=f"{PRIVATE_PUBLISHER_NOTE} URL: https://www.springer.com/journal/10051",
        fetcher=fetch_private_placeholder,
    ),
    "ieee_transactions_on_neural_networks": SourceDefinition(
        source_id="ieee_transactions_on_neural_networks",
        label="IEEE Trans. on Neural Networks",
        main_category="Academic & Preprints",
        sub_category="CS, ML & AI",
        homepage_url="https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5962385",
        access="Private",
        notes="Private source. Reach out to IEEE Xplore account admins or your institutional library. URL: https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5962385",
        fetcher=fetch_private_placeholder,
    ),
    "ieee_transactions_on_signal_processing": SourceDefinition(
        source_id="ieee_transactions_on_signal_processing",
        label="IEEE Trans. on Signal Processing",
        main_category="Academic & Preprints",
        sub_category="CS, ML & AI",
        homepage_url="https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=78",
        access="Private",
        notes="Private source. Reach out to IEEE Xplore account admins or your institutional library. URL: https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=78",
        fetcher=fetch_private_placeholder,
    ),
    "plos_computational_biology": SourceDefinition(
        source_id="plos_computational_biology",
        label="PLOS Computational Biology",
        main_category="Academic & Preprints",
        sub_category="Biology & Complex Systems",
        homepage_url="https://journals.plos.org/ploscompbiol/",
        access="Public",
        notes="Dedicated adapter for public PLOS Computational Biology article and printable PDF links.",
        fetcher=fetch_plos_computational_biology,
    ),
    "journal_of_artificial_societies_and_social_simulation": SourceDefinition(
        source_id="journal_of_artificial_societies_and_social_simulation",
        label="Journal of Artificial Societies and Social Simulation",
        main_category="Academic & Preprints",
        sub_category="Biology & Complex Systems",
        homepage_url="https://jasss.soc.surrey.ac.uk/",
        access="Public",
        notes="Dedicated adapter for the latest JASSS issue contents and generated PDF links.",
        fetcher=fetch_jasss,
    ),
    "biosystems": SourceDefinition(
        source_id="biosystems",
        label="BioSystems",
        main_category="Academic & Preprints",
        sub_category="Biology & Complex Systems",
        homepage_url="https://www.sciencedirect.com/journal/biosystems",
        access="Private",
        notes=f"{PRIVATE_PUBLISHER_NOTE} URL: https://www.sciencedirect.com/journal/biosystems",
        fetcher=fetch_private_placeholder,
    ),
    "journal_of_econometrics": SourceDefinition(
        source_id="journal_of_econometrics",
        label="Journal of Econometrics",
        main_category="Academic & Preprints",
        sub_category="Math, Stats & Ops",
        homepage_url="https://www.sciencedirect.com/journal/journal-of-econometrics",
        access="Private",
        notes=f"{PRIVATE_PUBLISHER_NOTE} URL: https://www.sciencedirect.com/journal/journal-of-econometrics",
        fetcher=fetch_private_placeholder,
    ),
    "stochastic_processes_and_their_applications": SourceDefinition(
        source_id="stochastic_processes_and_their_applications",
        label="Stochastic Processes and their Applications",
        main_category="Academic & Preprints",
        sub_category="Math, Stats & Ops",
        homepage_url="https://www.sciencedirect.com/journal/stochastic-processes-and-their-applications",
        access="Private",
        notes=f"{PRIVATE_PUBLISHER_NOTE} URL: https://www.sciencedirect.com/journal/stochastic-processes-and-their-applications",
        fetcher=fetch_private_placeholder,
    ),
    "aqr_capital_management_insights": SourceDefinition(
        source_id="aqr_capital_management_insights",
        label="AQR Capital Management Insights",
        main_category="Industry & Practitioner",
        sub_category="Trading Firms & Hedge Funds",
        homepage_url="https://www.aqr.com/Insights",
        access="Public",
        notes="Best-effort HTML discovery from the public insights site.",
        fetcher=fetch_generic_html,
    ),
    "oxford_man_institute": SourceDefinition(
        source_id="oxford_man_institute",
        label="Oxford-Man Institute",
        main_category="Industry & Practitioner",
        sub_category="Trading Firms & Hedge Funds",
        homepage_url="https://www.oxford-man.ox.ac.uk/research/publications/",
        access="Public",
        notes="Best-effort HTML discovery from the public publications index.",
        fetcher=fetch_generic_html,
    ),
    "two_sigma_insights": SourceDefinition(
        source_id="two_sigma_insights",
        label="Two Sigma Insights",
        main_category="Industry & Practitioner",
        sub_category="Trading Firms & Hedge Funds",
        homepage_url="https://www.twosigma.com/insights/",
        access="Public",
        notes="Best-effort HTML discovery from the public insights site.",
        fetcher=fetch_generic_html,
    ),
    "jane_street_tech_blog": SourceDefinition(
        source_id="jane_street_tech_blog",
        label="Jane Street Tech Blog",
        main_category="Industry & Practitioner",
        sub_category="Trading Firms & Hedge Funds",
        homepage_url="https://blog.janestreet.com/",
        access="Public",
        notes="Best-effort HTML discovery from the public blog landing page.",
        fetcher=fetch_generic_html,
    ),
    "optiver_insights": SourceDefinition(
        source_id="optiver_insights",
        label="Optiver Insights",
        main_category="Industry & Practitioner",
        sub_category="Trading Firms & Hedge Funds",
        homepage_url="https://optiver.com/insights/",
        access="Public",
        notes="Best-effort HTML discovery from the public insights site.",
        fetcher=fetch_generic_html,
    ),
    "cfm_capital_fund_management": SourceDefinition(
        source_id="cfm_capital_fund_management",
        label="CFM (Capital Fund Management)",
        main_category="Industry & Practitioner",
        sub_category="Trading Firms & Hedge Funds",
        homepage_url="https://www.cfm.com/insights/",
        access="Public",
        notes="Best-effort HTML discovery from the public insights site.",
        fetcher=fetch_generic_html,
    ),
    "citadel_securities_market_insights": SourceDefinition(
        source_id="citadel_securities_market_insights",
        label="Citadel Securities Market Insights",
        main_category="Industry & Practitioner",
        sub_category="Trading Firms & Hedge Funds",
        homepage_url="https://www.citadelsecurities.com/news-and-insights/",
        access="Public",
        notes="Best-effort HTML discovery from the public news and insights site.",
        fetcher=fetch_generic_html,
    ),
    "robeco_quantitative_research": SourceDefinition(
        source_id="robeco_quantitative_research",
        label="Robeco Quantitative Research",
        main_category="Industry & Practitioner",
        sub_category="Trading Firms & Hedge Funds",
        homepage_url="https://www.robeco.com/en-int/insights/quantitative-investing",
        access="Public",
        notes="Best-effort HTML discovery from the public insights page.",
        fetcher=fetch_generic_html,
    ),
    "quantresearch_org_lopez_de_prado": SourceDefinition(
        source_id="quantresearch_org_lopez_de_prado",
        label="QuantResearch.org (Lopez de Prado)",
        main_category="Industry & Practitioner",
        sub_category="Trading Firms & Hedge Funds",
        homepage_url="https://www.quantresearch.org/",
        access="Public",
        notes="Best-effort HTML discovery from the public site.",
        fetcher=fetch_generic_html,
    ),
    "winton_group_research": SourceDefinition(
        source_id="winton_group_research",
        label="Winton Group Research",
        main_category="Industry & Practitioner",
        sub_category="Trading Firms & Hedge Funds",
        homepage_url="https://www.winton.com/research",
        access="Public",
        notes="Best-effort HTML discovery from the public research page.",
        fetcher=fetch_generic_html,
    ),
    "kaiko_quant_white_papers": SourceDefinition(
        source_id="kaiko_quant_white_papers",
        label="Kaiko Quant White Papers",
        main_category="Industry & Practitioner",
        sub_category="Data Providers & Exchanges",
        homepage_url="https://www.kaiko.com/resources/quantitative-white-papers",
        access="Public",
        notes="Best-effort HTML discovery from the public resource page.",
        fetcher=fetch_generic_html,
    ),
    "cme_group_research": SourceDefinition(
        source_id="cme_group_research",
        label="CME Group Research",
        main_category="Industry & Practitioner",
        sub_category="Data Providers & Exchanges",
        homepage_url="https://www.cmegroup.com/education/articles-and-reports.html",
        access="Public",
        notes="Best-effort HTML discovery from the public research page.",
        fetcher=fetch_generic_html,
    ),
    "jpm_macro_qds": SourceDefinition(
        source_id="jpm_macro_qds",
        label="J.P. Morgan Macro QDS",
        main_category="Industry & Practitioner",
        sub_category="Sell-Side Global Quant",
        homepage_url="https://www.jpmm.com/",
        access="Private",
        notes="Private source. Reach out to your J.P. Morgan sales representative or institutional account team. URL: https://www.jpmm.com/",
        fetcher=fetch_private_placeholder,
    ),
    "morgan_stanley_qds": SourceDefinition(
        source_id="morgan_stanley_qds",
        label="Morgan Stanley QDS",
        main_category="Industry & Practitioner",
        sub_category="Sell-Side Global Quant",
        homepage_url="https://www.morganstanley.com/ideas",
        access="Private",
        notes="Private source. Reach out to your Morgan Stanley sales representative or institutional account team. URL: https://www.morganstanley.com/ideas",
        fetcher=fetch_private_placeholder,
    ),
    "goldman_sachs_marquee": SourceDefinition(
        source_id="goldman_sachs_marquee",
        label="Goldman Sachs Marquee",
        main_category="Industry & Practitioner",
        sub_category="Sell-Side Global Quant",
        homepage_url="https://marquee.gs.com/",
        access="Private",
        notes="Private source. Reach out to your Goldman Sachs sales representative or institutional Marquee account team. URL: https://marquee.gs.com/",
        fetcher=fetch_private_placeholder,
    ),
}


def list_sources() -> list[SourceDefinition]:
    return list(SOURCE_REGISTRY.values())


def list_public_academic_sources() -> list[SourceDefinition]:
    return [
        source
        for source in SOURCE_REGISTRY.values()
        if source.access.lower() == "public" and source.main_category == "Academic & Preprints"
    ]
